### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by rhaynes74** [Gruntfuggly/calendar#7]
Hi folks,   I had the calendar extension installed and working.  I deleted my credentials file by accident and decided to uninstall and reinstall the calendar extension - now I am having installation instructions:

I have followed the first 5 steps below. 

Visit https://developers.google.com/calendar/quickstart/nodejs
Click the Enable the Google Calendar API button in Step 1.
Click the DOWNLOAD CLIENT CONFIGURATION button and save the file somewhere.
Update the calendar.google.credentialsFile setting to point to the saved file.
Press F1 and run the command Calendar: Authorize
Click the Get Authorization Code button and follow the instructions in your browser. Note: Google will warn you that the application is not verified, but you're the only person who will be accessing your calendar. Click Advanced and then click Go to Quickstart (unsafe).
Copy the code that google generates.
Press F1 and run the command Calendar: Authorize again.
Click the Enter Authorization Code and paste in the code that google gave you.

But after running the command Calendar: Authorize I don't see any "get authorization code button", nothing happens.   Any ideas as to what is happening? 

Best,
R Haynes

**Comment by Gruntfuggly** [comment]
Not sure why it's not working, but you can try "Calendar: Reset Cache", which should clear any stored data. Reloading the window should then start you from scratch.

**Comment by rhaynes74** [comment]
That worked!  Many thanks!
